name: argovis_demos

dependencies:
  - python=3.9
  - jupyter
  - jupyterlab
  - ipython
  - ipykernel
  - requests
  - cartopy
  - pandas
  - pip
  - scipy
  - numpy
  - xarray
  - pip:
    - svgpath2mpl

channels:
    - conda-forge
    - defaults
    - conda-forge/label/broken
